name: telegram-bot-rum
region: nyc
services:
  - name: bot
    github:
      branch: main
      deploy_on_push: true
      repo: your-username/rum
    environment_slug: node-js
    envs:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
        type: SECRET
      - key: WEBHOOK_DOMAIN
        value: ${APP_URL}
      - key: PORT
        value: "8080"
    health_check:
      http_path: /health
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    run_command: npm start
    build_command: npm install
